Repository GDSC-DGU/2024-SolutionChallenge-EarthAndI, pull requests merged in 2024-05, with the labels that each got.

#65 ⚡ Feature - Coming Soon Challenge Screen
  app/assets/icons/buy_local_products.png
  app/assets/icons/climate_control.png
  app/assets/icons/down.svg
  app/assets/icons/recycle.png
  app/assets/icons/ride_bike.png
  app/assets/icons/unplug_devices.png
  app/assets/icons/use_energy_efficiency.png
  app/assets/icons/use_led.png
  app/assets/icons/use_public_transport.png
  app/assets/icons/use_reusable_container.png
  app/assets/images/coming_soon_challenge.png
  app/lib/bindings/coming_soon_challenge_binding.dart
  app/lib/domains/type/e_challenge.dart
  app/lib/models/load_map/challenge_history_state.dart
  app/lib/utilities/static/app_pages.dart
  app/lib/utilities/static/app_routes.dart
  app/lib/utilities/translation/app_translations.dart
  app/lib/utilities/translation/e_challenge_translations.dart
  app/lib/view_models/coming_soon_challenge/coming_soon_challenge_view_model.dart
  app/lib/views/coming_soon_challenge/coming_soon_challenge_screen.dart
  app/lib/views/coming_soon_challenge/static/coming_soon_challenge_states.dart
  app/lib/views/load_map/load_map_screen.dart
  app/lib/widgets/appbar/default_appbar.dart
  app/lib/widgets/dialog/challenge_dialog.dart
Labels: feature, JWH

#69 ✨ Fix - Data Sync Error
  app/lib/providers/follow/follow_provider_impl.dart
  app/lib/utilities/translation/app_translations.dart
  app/lib/views/ranking/ranking_screen.dart
Labels: SHJ, fix

#70 ✨ 🚑 [ Fix, Feature ] - Token Condition Error, Message API
  server/trigger_and_notification_api/functions/index.js
  server/trigger_and_notification_api/package-lock.json
  server/trigger_and_notification_api/package.json
Labels: feature, SHJ, fix

#72 🚑 Fix - Time Error
  server/trigger_and_notification_api/functions/index.js
Labels: SHJ, fix

#73 ✨ Feature - Apply DIP, Message API
  app/lib/bindings/init_binding.dart
  app/lib/providers/notification/notification_provider.dart
  app/lib/providers/notification/notification_provider_impl.dart
  app/lib/repositories/action_history/action_history_repository.dart
  app/lib/repositories/action_history/action_history_repository_impl.dart
  app/lib/repositories/analysis/analysis_repository.dart
  app/lib/repositories/analysis/analysis_repository_impl.dart
  app/lib/repositories/challenge_history/challenge_history_repository.dart
  app/lib/repositories/challenge_history/challenge_history_repository_impl.dart
  app/lib/repositories/follow/follow_repository.dart
  app/lib/repositories/follow/follow_repository_impl.dart
  app/lib/repositories/friend/friend_repository.dart
  app/lib/repositories/friend/friend_repository_impl.dart
  app/lib/repositories/notification/notification_repository.dart
  app/lib/repositories/notification/notification_repository_impl.dart
  app/lib/repositories/user/user_repository.dart
  app/lib/repositories/user/user_repository_impl.dart
  app/lib/utilities/translation/app_translations.dart
  app/lib/view_models/challenge_authentication/challenge_authentication_view_model.dart
  app/lib/view_models/follow/follow_view_model.dart
  app/lib/view_models/home/home_view_model.dart
  app/lib/view_models/load_map/load_map_view_model.dart
  app/lib/view_models/profile/profile_view_model.dart
  app/lib/view_models/ranking/ranking_view_model.dart
  app/lib/view_models/setting/setting_view_model.dart
  app/lib/view_models/sign_in/sign_in_view_model.dart
  app/lib/view_models/user_search/user_search_view_model.dart
  app/lib/views/ranking/ranking_screen.dart
Labels: feature, SHJ

#74 ✨ Develop - Version Up
  app/pubspec.yaml
Labels: SHJ, Deploy

#76 🚑 Fix - DI, State Error
  app/lib/providers/follow/follow_provider_impl.dart
  app/lib/view_models/setting/setting_view_model.dart
  app/pubspec.yaml
Labels: SHJ, fix

#80 🐛 Fix - OnTap Rank Item Error
  app/lib/views/ranking/ranking_screen.dart
Labels: SHJ, fix

#82 🚀 Deploy - Change Version
  app/pubspec.yaml
Labels: Deploy

#83 ⚡ Docs - Update README
  README.md
  app/README.md
Labels: documentation, JWH

#86 📝 Docs - Update README.md
  server/README.md
Labels: documentation

#87 🚀 Deploy - Version 1.2.0
  server/README.md
  server/trigger_and_notification_api/functions/index.js
  server/trigger_and_notification_api/package-lock.json
  server/trigger_and_notification_api/package.json
Labels: Deploy

#89 📝 Docs - Update README.md
  README.md
Labels: documentation
