Repository GDSC-DGU/2024-SolutionChallenge-EarthAndI, pull requests merged in 2024-02, with the labels that each got.

#5 ✨ Feature - Bottom Navigation Bar, FAB, GreyScale
  app/assets/icons/home.svg
  app/assets/icons/load_map.svg
  app/assets/icons/profile.svg
  app/assets/icons/verification_echo.svg
  app/lib/bindings/home_binding.dart
  app/lib/bindings/load_map_binding.dart
  app/lib/bindings/profile_binding.dart
  app/lib/bindings/root_binding.dart
  app/lib/utilities/functions/dev_on_log.dart
  app/lib/utilities/functions/temp
  app/lib/view_models/home/home_view_model.dart
  app/lib/view_models/load_map/load_map_view_model.dart
  app/lib/view_models/profile/profile_view_model.dart
  app/lib/view_models/root/root_view_model.dart
  app/lib/views/home/home_screen.dart
  app/lib/views/load_map/load_map_screen.dart
  app/lib/views/profile/profile_screen.dart
  app/lib/views/root/root_screen.dart
  app/lib/views/root/widgets/custom_bottom_navigation_bar.dart
  app/lib/views/root/widgets/custom_bottom_navigation_bar_shape.dart
  app/lib/views/root/widgets/root_floating_action_button.dart
  app/lib/views/root/widgets/verification_grey_barrier.dart
  app/lib/views/root/widgets/verification_menu.dart
  app/lib/widgets/line/infinity_line.dart
Labels: feature, SHJ

#6 ⚡ Feature - App bar, Back App bar, Back App bar with plus button
  app/assets/icons/arrow_back.svg
  app/assets/icons/plus.svg
  app/ios/Podfile.lock
  app/lib/utilities/system/font_system.dart
  app/lib/widgets/appbar/custom_icon_button.dart
  app/lib/widgets/appbar/default_appbar.dart
  app/lib/widgets/appbar/default_back_appbar.dart
Labels: feature, JWH

#8 Feature - Sync IPhone Development Files
  app/ios/Runner.xcodeproj/project.pbxproj
Labels: documentation, SHJ

#10 [ Feature ] - Home Screen
  app/android/app/build.gradle
  app/android/app/src/main/AndroidManifest.xml
  app/assets/images/character.svg
  app/assets/images/ground.svg
  app/assets/images/sunny.jpg
  app/assets/images/temp
  app/ios/Podfile.lock
  app/ios/Runner/Info.plist
  app/lib/models/home/carbon_cloud_state.dart
  app/lib/models/home/speech_state.dart
  app/lib/view_models/home/home_view_model.dart
  app/lib/view_models/root/root_view_model.dart
  app/lib/views/home/home_screen.dart
  app/lib/views/home/shapes/floor_layer_clipper.dart
  app/lib/views/home/shapes/speech_bubble_clipper.dart
  app/lib/views/home/widgets/carbon_cloud.dart
  app/lib/views/home/widgets/speech_bubble.dart
  app/lib/views/root/root_screen.dart
  app/lib/views/root/shapes/custom_bottom_navigation_bar_shape.dart
  app/lib/views/root/widgets/custom_bottom_navigation_bar.dart
  app/lib/views/root/widgets/overlay_grey_barrier.dart
  app/lib/views/root/widgets/root_floating_action_button.dart
  app/lib/views/root/widgets/verification_grey_barrier.dart
  app/lib/views/root/widgets/verification_menu.dart
  app/pubspec.yaml
Labels: feature, SHJ

#15 ✨ Feature: Data Binding
  app/.gitignore
  app/.metadata
  app/android/app/build.gradle
  app/android/app/src/main/AndroidManifest.xml
  app/ios/Podfile
  app/ios/Podfile.lock
  app/ios/Runner.xcodeproj/project.pbxproj
  app/ios/Runner/Info.plist
  app/ios/Runner/Runner.entitlements
  app/ios/Runner/RunnerRelease.entitlements
  app/lib/apps/database/local_database.dart
  app/lib/apps/database/local_database.g.dart
  app/lib/apps/database/temp
  app/lib/apps/factory/local_database_factory.dart
  app/lib/apps/factory/local_storage_factory.dart
  app/lib/apps/factory/temp
  app/lib/apps/firebase/persistent
  app/lib/domains/dao/action_history_dao.dart
  app/lib/domains/dao/action_history_dao.g.dart
  app/lib/domains/dao/challenge_history_dao.dart
  app/lib/domains/dao/challenge_history_dao.g.dart
  app/lib/domains/entity/action_history.dart
  app/lib/domains/entity/challenge_history.dart
  app/lib/domains/type/e_action.dart
  app/lib/domains/type/e_challenge.dart
  app/lib/main.dart
  app/lib/view_models/root/root_view_model.dart
  app/lib/views/home/home_screen.dart
  app/lib/views/root/widgets/root_floating_action_button.dart
  app/lib/widgets/button/temp_health_btn.dart
  app/lib/widgets/button/temp_login_btn.dart
  app/pubspec.yaml
  app/web/favicon.png
  app/web/icons/Icon-192.png
  app/web/icons/Icon-512.png
  app/web/icons/Icon-maskable-192.png
  app/web/icons/Icon-maskable-512.png
  app/web/index.html
  app/web/manifest.json
Labels: feature, SHJ

#21 ✨ 🎨 🐛 Feature, Fix, Design - Connect Data, Change DataBase Schema, Manage Memory
  app/assets/images/analysis/1_1_1.svg
  app/assets/images/analysis/1_1_2.svg
  app/assets/images/analysis/1_2_1.svg
  app/assets/images/analysis/1_2_2.svg
  app/assets/images/analysis/2_1_1.svg
  app/assets/images/analysis/2_1_2.svg
  app/assets/images/analysis/2_2_1.svg
  app/assets/images/analysis/2_2_2.svg
  app/assets/images/character.svg
  app/assets/images/character/1_1_1_1.svg
  app/assets/images/character/1_1_1_2.svg
  app/assets/images/character/1_1_2_1.svg
  app/assets/images/character/1_1_2_2.svg
  app/assets/images/character/1_2_1_1.svg
  app/assets/images/character/1_2_1_2.svg
  app/assets/images/character/1_2_2_1.svg
  app/assets/images/character/1_2_2_2.svg
  app/assets/images/character/2_1_1_1.svg
  app/assets/images/character/2_1_1_2.svg
  app/assets/images/character/2_1_2_1.svg
  app/assets/images/character/2_1_2_2.svg
  app/assets/images/character/2_2_1_1.svg
  app/assets/images/character/2_2_1_2.svg
  app/assets/images/character/2_2_2_1.svg
  app/assets/images/character/2_2_2_2.svg
  app/assets/images/ground.svg
  app/assets/images/sunny.jpg
  app/assets/riv/record_animation_for_vox.riv
  app/ios/Podfile.lock
  app/lib/apps/main_app.dart
  app/lib/domains/converter/e_type_converter.dart
  app/lib/domains/dao/user_dao.dart
  app/lib/domains/type/e_action.dart
  app/lib/domains/type/e_challenge.dart
  app/lib/main.dart
  app/lib/models/home/analysis_state.dart
  app/lib/models/home/carbon_cloud_state.dart
  app/lib/models/home/character_state.dart
  app/lib/models/home/speech_state.dart
  app/lib/providers/user_local_provider.dart
  app/lib/repositories/action_history_repository.dart
  app/lib/repositories/user_repository.dart
  app/lib/utilities/static/app_translations.dart
  app/lib/utilities/static/carbon_cloud_texts.dart
  app/lib/utilities/static/character_translations.dart
  app/lib/utilities/static/e_action_translations.dart
  app/lib/utilities/system/color_system.dart
  app/lib/view_models/home/home_view_model.dart
  app/lib/view_models/root/root_view_model.dart
  app/lib/views/home/home_screen.dart
  app/lib/views/home/widgets/carbon_cloud.dart
  app/lib/views/home/widgets/speech_bubble.dart
  app/lib/views/home/widgets/speech_recognize_bottom_sheet.dart
  app/lib/views/root/root_screen.dart
  app/lib/views/root/widgets/custom_bottom_navigation_bar.dart
  app/lib/views/root/widgets/root_floating_action_button.dart
  app/lib/widgets/button/temp_health_btn.dart
  app/pubspec.yaml
Labels: bug, feature, SHJ

#22 ⚡ Feature - My Page Screen v2
  app/lib/bindings/profile_binding.dart
  app/lib/models/profile/weekly_calendar_state.dart
  app/lib/view_models/profile/profile_view_model.dart
  app/lib/view_models/profile/weekly_calendar_view_model.dart
  app/lib/views/profile/profile_screen.dart
  app/lib/views/profile/widgets/custom_carbon_bar_chart.dart
  app/lib/views/profile/widgets/user_history.dart
  app/lib/views/profile/widgets/user_profile.dart
  app/lib/views/profile/widgets/weekly_calendar.dart
  app/pubspec.yaml
Labels: feature, JWH

#27 ⚡ Feature - My Page Data Connection
  app/assets/images/thumbnail/data_usage_thumbnail.png
  app/assets/images/thumbnail/walking_thumbnail.png
  app/lib/bindings/profile_binding.dart
  app/lib/domains/dao/action_history_dao.dart
  app/lib/models/profile/daily_carbon_state.dart
  app/lib/models/profile/total_carbon_state.dart
  app/lib/providers/action_history_local_provider.dart
  app/lib/repositories/action_history_repository.dart
  app/lib/repositories/user_repository.dart
  app/lib/utilities/static/e_action_translations.dart
  app/lib/view_models/profile/profile_view_model.dart
  app/lib/view_models/profile/weekly_calendar_view_model.dart
  app/lib/views/challenge_authentication/challenge_authentication_screen.dart
  app/lib/views/load_map/widgets/challenge_dialog.dart
  app/lib/views/load_map/widgets/challenge_list.dart
  app/lib/views/load_map/widgets/load_map_carousel.dart
  app/lib/views/profile/widgets/custom_carbon_bar_chart.dart
  app/lib/views/profile/widgets/history_item.dart
  app/lib/views/profile/widgets/user_history.dart
  app/lib/views/profile/widgets/user_profile.dart
  app/lib/views/profile/widgets/weekly_calendar.dart
  app/pubspec.yaml
Labels: feature, JWH

#30 ⚡ Feature - Load Map Data Connection
  app/assets/config/temp
  app/assets/icons/delete_email.png
  app/assets/icons/use_cold_water.png
  app/assets/icons/use_eco_friendly_products.png
  app/lib/bindings/init_binding.dart
  app/lib/domains/converter/e_type_converter.dart
  app/lib/domains/dao/challenge_history_dao.dart
  app/lib/domains/dao/user_dao.dart
  app/lib/domains/type/e_challenge.dart
  app/lib/models/load_map/challenge_history_state.dart
  app/lib/providers/challenge_history_local_provider.dart
  app/lib/repositories/challenge_history_repository.dart
  app/lib/repositories/user_repository.dart
  app/lib/utilities/static/app_translations.dart
  app/lib/utilities/static/e_challenge_translations.dart
  app/lib/view_models/load_map/load_map_view_model.dart
  app/lib/view_models/root/root_view_model.dart
  app/lib/views/challenge_authentication/challenge_authentication_screen.dart
  app/lib/views/load_map/load_map_screen.dart
  app/lib/views/load_map/widgets/challenge_dialog.dart
  app/lib/views/load_map/widgets/challenge_list.dart
  app/lib/views/load_map/widgets/load_map_carousel.dart
  app/lib/views/root/root_screen.dart
Labels: feature, JWH

#37 ⚡ Feature, Fix, Design - Challenge API Connection, Change Current Challenge
  app/assets/icons/clear_challenge.png
  app/assets/icons/clear_challenge.svg
  app/assets/icons/earth.svg
  app/assets/icons/eat_vegetarian.png
  app/assets/icons/failed_challenge.svg
  app/assets/icons/thumbnail.png
  app/lib/bindings/init_binding.dart
  app/lib/domains/type/e_challenge.dart
  app/lib/providers/challenge_authentication/challenge_authentication_connect.dart
  app/lib/providers/challenge_authentication/challenge_authentication_provider_impl.dart
  app/lib/providers/challenge_authentication_provider.dart
  app/lib/repositories/challenge_authentication_repository.dart
  app/lib/repositories/challenge_history_repository.dart
  app/lib/repositories/user_repository.dart
  app/lib/utilities/static/e_challenge_translations.dart
  app/lib/view_models/challenge_authentication/challenge_authentication_view_model.dart
  app/lib/view_models/load_map/load_map_view_model.dart
  app/lib/view_models/root/root_view_model.dart
  app/lib/views/challenge_authentication/challenge_authentication_screen.dart
  app/lib/views/challenge_authentication/pageview/loading_screen.dart
  app/lib/views/challenge_authentication/pageview/result_failed_screen.dart
  app/lib/views/challenge_authentication/pageview/result_success_screen.dart
  app/lib/views/load_map/load_map_screen.dart
  app/lib/views/load_map/widgets/challenge_dialog.dart
  app/lib/views/load_map/widgets/challenge_list.dart
  app/lib/views/load_map/widgets/load_map_carousel.dart
  app/lib/views/root/root_screen.dart
Labels: bug, feature, JWH

#45 🎨 Refacto - Memory Optimization
  app/lib/apps/main_app.dart
  app/lib/bindings/init_binding.dart
  app/lib/domains/dao/action_history_dao.dart
  app/lib/domains/dao/user_dao.dart
  app/lib/domains/type/e_challenge.dart
  app/lib/main.dart
  app/lib/models/load_map/challenge_history_state.dart
  app/lib/providers/action/action_history_local_provider.dart
  app/lib/repositories/action_history_repository.dart
  app/lib/repositories/challenge_history_repository.dart
  app/lib/repositories/user_repository.dart
  app/lib/utilities/translation/app_translations.dart
  app/lib/utilities/translation/common_translations.dart
  app/lib/utilities/translation/e_challenge_translations.dart
  app/lib/view_models/home/home_view_model.dart
  app/lib/view_models/load_map/load_map_view_model.dart
  app/lib/view_models/profile/profile_view_model.dart
  app/lib/views/load_map/widgets/challenge_history_item.dart
  app/lib/widgets/dialog/challenge_dialog.dart
Labels: SHJ, refactor

#48 🚀 Deploy - Server(FaaS) Version 1.1.0
  ai/api-challenge.py
  ai/api-interaction.py
Labels: Deploy

#50 🐛 Fix - Follow PreProcessing Error
  app/lib/providers/follow/follow_provider_impl.dart
  app/lib/repositories/user_repository.dart
  app/lib/views/setting/widgets/custom_time_picker_dialog.dart
  app/pubspec.yaml
Labels: bug, SHJ

#53 🐛 Fix - Splash Error
  app/lib/apps/main_app.dart
  app/lib/main.dart
  app/lib/repositories/user_repository.dart
  app/lib/utilities/functions/notification_util.dart
  app/lib/utilities/translation/common_translations.dart
  app/lib/view_models/home/home_view_model.dart
  app/pubspec.yaml
Labels: SHJ

#55 🐛 fix: Notification Content Error
  app/lib/utilities/functions/notification_util.dart
  app/lib/utilities/translation/app_translations.dart
Labels: bug

#57 🚀 chore - version 1.1.3+1 -> 1.1.3+2
  app/pubspec.yaml
Labels: documentation, SHJ

#56 🎨 📝 refactor - trigger and notification api
  server/.gitignore
  server/README.md
  server/analysis_api/analysis-image.py
  server/analysis_api/analysis-text.py
  server/trigger_and_notification_api/firebase.json
  server/trigger_and_notification_api/functions/index.js
  server/trigger_and_notification_api/functions/package-lock.json
  server/trigger_and_notification_api/functions/package.json
  server/trigger_and_notification_api/public/404.html
  server/trigger_and_notification_api/public/index.html
Labels: documentation, feature, SHJ

#52 ⚡ Docs - Update README.md
  README.md
Labels: documentation

#60 📝 Documentation - Create App README.md
  app/README.md
Labels: documentation, SHJ

#58 🚀 Deploy - Server 1.1.3+2
  ai/temp
  server/.gitignore
  server/README.md
  server/analysis_api/analysis-image.py
  server/analysis_api/analysis-text.py
  server/trigger_and_notification_api/firebase.json
  server/trigger_and_notification_api/functions/index.js
  server/trigger_and_notification_api/functions/package-lock.json
  server/trigger_and_notification_api/functions/package.json
  server/trigger_and_notification_api/public/404.html
  server/trigger_and_notification_api/public/index.html
Labels: Deploy

#61 🚀 Deploy - Version 1.1.3+2
  README.md
  app/README.md
  app/lib/utilities/functions/notification_util.dart
  app/lib/utilities/translation/app_translations.dart
  app/pubspec.yaml
Labels: Deploy
